#!/usr/bin/env python3
# Copyright 2026 Argus Security
# Licensed under the GNU Affero General Public License v3.0
# See LICENSE file for details

"""Generate the check reference from the check registry.

    python scripts/generate_check_reference.py          # rewrite docs/checks.md and wiki/Check-Reference.md
    python scripts/generate_check_reference.py --check  # exit 1 if either file is out of date (for CI)

The registry is the single source of truth; never edit the generated files by hand.
"""

import argparse
import collections
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from gws_auditor.checks.registry import CheckRegistry  # noqa: E402

TARGETS = [ROOT / "docs" / "checks.md", ROOT / "wiki" / "Check-Reference.md"]

FRAMEWORKS = [
    ("CIS", "CIS Google Workspace Foundations Benchmark v1.3.0"),
    ("CISA", "CISA SCuBA Baselines for Google Workspace"),
    ("GOOGLE", "Google Security Checklist for Medium & Large Businesses"),
    ("OTHER", "Additional best-practice checks"),
]
LICENSES = {
    "business_standard": "Business Standard+", "business_plus": "Business Plus+",
    "enterprise_standard": "Enterprise Standard+", "enterprise_plus": "Enterprise Plus",
    "assured_controls": "Assured Controls add-on",
}
SEVERITY_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW"]


def _id_key(check_id: str):
    """Sort CIS-3.1.10 after CIS-3.1.9 and ADD-9 before ADD-10."""
    parts = check_id.replace("-", ".").split(".")
    return [(0, int(p)) if p.isdigit() else (1, p) for p in parts]


def render() -> str:
    checks = CheckRegistry().get_all_checks()
    sev = lambda m: getattr(m.severity, "value", str(m.severity))  # noqa: E731
    by_source = collections.Counter(m.source for m in checks)
    by_level = collections.Counter(m.level for m in checks)
    by_sev = collections.Counter(sev(m) for m in checks)
    unscored = sum(1 for m in checks if not m.scored)

    out = [
        "# GWS Security Auditor - Complete Check Reference",
        "",
        "<!-- GENERATED by scripts/generate_check_reference.py from the check registry. Do not edit by hand. -->",
        "",
        "## Overview",
        "",
        f"The GWS Security Auditor implements **{len(checks)} security checks** across four frameworks:",
        "",
        "| Framework | Full Name | Checks |",
        "|-----------|-----------|-------:|",
    ]
    out += [f"| **{code}** | {name} | {by_source.get(code, 0)} |" for code, name in FRAMEWORKS]
    out += [
        f"| | **Total** | **{len(checks)}** |",
        "",
        "## Check Levels",
        "",
        f"- **L1 (Level 1)** -- {by_level.get('L1', 0)} checks. Baseline security settings that should be applied to all "
        "organizations. Minimal performance impact, broad applicability.",
        f"- **L2 (Level 2)** -- {by_level.get('L2', 0)} checks. Advanced security settings for organizations with higher "
        "security requirements. May restrict functionality or require additional configuration.",
        "",
        "## Severity",
        "",
        "| Severity | Checks |",
        "|----------|-------:|",
    ]
    out += [f"| **{s}** | {by_sev.get(s, 0)} |" for s in SEVERITY_ORDER]
    out += [
        "",
        f"{unscored} checks are informational (inventory/review) and do not affect the posture score; they are marked "
        "*unscored* below.",
        "",
        "## Check Statuses",
        "",
        "| Status | Meaning |",
        "|--------|---------|",
        "| **PASS** | Configuration meets the benchmark requirement |",
        "| **FAIL** | Configuration does not meet the requirement |",
        "| **WARN** | Partial compliance or potential issue detected |",
        "| **PARTIAL** | Remaining violations sit only in OUs designated for external sharing |",
        "| **ERROR** | Check could not complete: an API error, or the data it needs was not collected |",
        "| **MANUAL** | Requires manual verification. Returned when a setting is not exposed by any Google API, or when "
        "its state cannot be determined from the collected data -- the auditor does not guess PASS or FAIL |",
        "| **NOT_APPLICABLE** | Check does not apply to this environment (for example, the licence tier lacks the feature) |",
        "",
        "Some settings are not exposed by the Cloud Identity Policy API. Where Google records changes to them in the admin "
        "audit log, the auditor infers the current value from the most recent change event; with no event inside the log "
        "window the result is MANUAL.",
        "",
        "---",
        "",
    ]

    sections = collections.defaultdict(list)
    for m in checks:
        sections[m.section].append(m)
    for section in sorted(sections):
        out += [f"## {section}", "", "| ID | Title | Level | Source | Severity | Notes |",
                "|----|-------|-------|--------|----------|-------|"]
        for m in sorted(sections[section], key=lambda m: _id_key(m.check_id)):
            notes = []
            if not m.scored:
                notes.append("unscored")
            if m.requires_license:
                notes.append(LICENSES.get(m.requires_license, m.requires_license))
            title = m.title.replace("|", "\\|")
            out.append(f"| {m.check_id} | {title} | {m.level} | {m.source} | {sev(m)} | {', '.join(notes)} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the generated files are out of date")
    args = parser.parse_args()
    content = render()
    stale = [p for p in TARGETS if not p.exists() or p.read_text(encoding="utf-8") != content]
    if args.check:
        for p in stale:
            print(f"out of date: {p.relative_to(ROOT)} (run scripts/generate_check_reference.py)")
        return 1 if stale else 0
    for p in TARGETS:
        p.write_text(content, encoding="utf-8")
        print(f"wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
